# Generated by Django 3.2.8 on 2021-10-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devawards', '0003_auto_20211026_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
