# Generated by Django 3.2.8 on 2021-10-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devawards', '0004_rename_name_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
