# Generated by Django 3.2.8 on 2021-10-27 11:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devawards', '0009_auto_20211027_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userpic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
