# Generated by Django 3.2.8 on 2021-10-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devawards', '0012_auto_20211028_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='likecount',
            field=models.BigIntegerField(default='0'),
        ),
    ]
